name: yarn
description: "Installs all yarn packages"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: yarn
  