name: Linting

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Lint
      run: |
        yarn
        yarn lint

  lint_code_formatter:
    runs-on: ubuntu-latest
    container: node
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Code-Formatting-Check
      run: |
        yarn
        yarn code-formatter-check
